// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-WUFh7zCGwGRNE5m0zOLLFb8oKylJ45I',
    appId: '1:355323866384:web:76b4b82931c6040342c995',
    messagingSenderId: '355323866384',
    projectId: 'nsbm-bus',
    authDomain: 'nsbm-bus.firebaseapp.com',
    storageBucket: 'nsbm-bus.appspot.com',
    measurementId: 'G-RYKFF1V3WP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHu2WzoI7xBRI_ECUbBqSlYDwHFdjxZBE',
    appId: '1:355323866384:android:c5dfb96e38f3dbbd42c995',
    messagingSenderId: '355323866384',
    projectId: 'nsbm-bus',
    storageBucket: 'nsbm-bus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNpqicSoqrgfreWxXl-Vha9jnaudL90Pk',
    appId: '1:355323866384:ios:a54633398bf9434842c995',
    messagingSenderId: '355323866384',
    projectId: 'nsbm-bus',
    storageBucket: 'nsbm-bus.appspot.com',
    iosBundleId: 'com.example.nsbmBus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNpqicSoqrgfreWxXl-Vha9jnaudL90Pk',
    appId: '1:355323866384:ios:dcb3b543222434e542c995',
    messagingSenderId: '355323866384',
    projectId: 'nsbm-bus',
    storageBucket: 'nsbm-bus.appspot.com',
    iosBundleId: 'com.example.nsbmBus.RunnerTests',
  );
}
